import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="bg-gray-800 text-slate-100 px-4 py-3 flex justify-between items-center">
          <div className="text-xl font-semibold">Woz_Ai(Basic)</div>
          <div className="space-x-2">
            <Link
              href="/"
              className="bg-slate-100 px-2 py-1 text-gray-800 font-semibold"
            >
              Completion
            </Link>
            <Link
              href="/chat"
              className="bg-slate-100 px-2 py-1 text-gray-800 font-semibold"
            >
              Chat
            </Link>
          </div>
        </header>
        {children}
      </body>
    </html>
  );
}
